// Generates the app icon and the menu bar cat from the drawing in Icon/cat-drawing.png.
// Run from the repo root:  swift Icon/make-icons.swift
//
// Outputs:
//   Resources/AppIcon.icns                   app icon (black lines, thin white edge, transparent)
//   Icon/AppIcon-256.png                     preview for the README
//   Sources/MacVitals/Views/CatImage.swift   menu bar cat (black on transparent), embedded as base64
import AppKit
import CoreImage
import CoreImage.CIFilterBuiltins

let ctx = CIContext()
let drawing = CIImage(contentsOf: URL(fileURLWithPath: "Icon/cat-drawing.png"))!

/// Upscales the drawing, thickens the strokes and turns the dark background transparent.
/// The result keeps the drawing's colors; callers tint it.
func cutout(thicken: Float) -> CIImage {
    let up = CIFilter.lanczosScaleTransform()
    up.inputImage = drawing; up.scale = 5; up.aspectRatio = 1
    var image = up.outputImage!
    let extent = image.extent
    if thicken > 0 {
        image = image.applyingFilter("CIMorphologyMaximum", parameters: ["inputRadius": thicken]).cropped(to: extent)
    }
    let mask = image.applyingFilter("CIMaximumComponent").applyingFilter("CIColorMatrix", parameters: [
        "inputRVector": CIVector(x: 3, y: 0, z: 0, w: 0), "inputGVector": CIVector(x: 3, y: 0, z: 0, w: 0),
        "inputBVector": CIVector(x: 3, y: 0, z: 0, w: 0), "inputBiasVector": CIVector(x: -0.75, y: -0.75, z: -0.75, w: 0),
    ]).applyingFilter("CIColorClamp")
    return image.applyingFilter("CIBlendWithMask", parameters: [
        kCIInputBackgroundImageKey: CIImage.empty(), kCIInputMaskImageKey: mask,
    ]).cropped(to: extent)
}

func nsImage(_ image: CIImage) -> NSImage {
    NSImage(cgImage: ctx.createCGImage(image, from: image.extent)!,
            size: NSSize(width: image.extent.width, height: image.extent.height))
}

func tinted(_ image: NSImage, _ color: NSColor) -> NSImage {
    NSImage(size: image.size, flipped: false) { rect in
        image.draw(in: rect)
        color.set()
        rect.fill(using: .sourceAtop)
        return true
    }
}

func png(_ image: NSImage, pixels: NSSize) -> Data {
    let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: Int(pixels.width), pixelsHigh: Int(pixels.height),
                               bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                               colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
    NSGraphicsContext.current?.imageInterpolation = .high
    image.draw(in: NSRect(origin: .zero, size: pixels))
    NSGraphicsContext.restoreGraphicsState()
    return rep.representation(using: .png, properties: [:])!
}

// App icon: the cat on the standard 1024 grid (content within the central 824 px).
let lines = nsImage(cutout(thicken: 5))
let edge = nsImage(cutout(thicken: 5).applyingFilter("CIMorphologyMaximum", parameters: ["inputRadius": 9]))
let icon = NSImage(size: NSSize(width: 1024, height: 1024), flipped: false) { _ in
    let height: CGFloat = 824, width = height * lines.size.width / lines.size.height
    let rect = NSRect(x: (1024 - width) / 2, y: 100, width: width, height: height)
    tinted(edge, .white).draw(in: rect)
    tinted(lines, .black).draw(in: rect)
    return true
}

let iconset = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("AppIcon.iconset")
try? FileManager.default.removeItem(at: iconset)
try! FileManager.default.createDirectory(at: iconset, withIntermediateDirectories: true)
for size in [16, 32, 128, 256, 512] {
    for scale in [1, 2] {
        let name = scale == 1 ? "icon_\(size)x\(size).png" : "icon_\(size)x\(size)@2x.png"
        let pixels = CGFloat(size * scale)
        try! png(icon, pixels: NSSize(width: pixels, height: pixels)).write(to: iconset.appendingPathComponent(name))
    }
}
let iconutil = Process()
iconutil.executableURL = URL(fileURLWithPath: "/usr/bin/iconutil")
iconutil.arguments = ["-c", "icns", iconset.path, "-o", "Resources/AppIcon.icns"]
try! iconutil.run(); iconutil.waitUntilExit()
try! png(icon, pixels: NSSize(width: 256, height: 256)).write(to: URL(fileURLWithPath: "Icon/AppIcon-256.png"))

// Menu bar cat: heavier lines so they survive at 18 pt, 4x resolution, black on transparent.
let heavy = nsImage(cutout(thicken: 12))
let menuHeight: CGFloat = 72
let menuCat = png(tinted(heavy, .black),
                  pixels: NSSize(width: (menuHeight * heavy.size.width / heavy.size.height).rounded(), height: menuHeight))
let swift = """
// Generated by Icon/make-icons.swift from Icon/cat-drawing.png. Don't edit by hand.

/// The menu bar cat: black lines on transparent, 72 px high (18 pt at 4x).
enum CatImage {
    static let pngBase64 = "\(menuCat.base64EncodedString())"
}

"""
try! swift.write(toFile: "Sources/MacVitals/Views/CatImage.swift", atomically: true, encoding: .utf8)
print("Wrote Resources/AppIcon.icns, Icon/AppIcon-256.png and Sources/MacVitals/Views/CatImage.swift (\(menuCat.count) bytes)")
